import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider } from "@/components/ui/sidebar";
import { DashboardSidebar } from "../../components/Sidebar";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Menu } from "lucide-react";
import { Toaster } from "@/components/ui/toaster";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <SidebarProvider>
      <div className="flex h-screen w-screen">
        <DashboardSidebar user={{ name: "Priyank Suthar" }} />

        <div className="flex-1 flex flex-col">
          <header className="flex items-center justify-between bg-purple-600 px-6 py-4 text-white rounded rounded-l-2xl">
            <div className="space-x-3 flex">
              <button>
                <Menu className="self-center" />
              </button>
              <h1 className="text-2xl font-extrabold">
                Creating Memories For a Lifetime
              </h1>
            </div>
            <div className="flex items-center gap-3">
              <span>Priyank Suthar</span>
              <Avatar>
                <AvatarImage src="" alt="Priyank Suthar" />
                <AvatarFallback>PS</AvatarFallback>
              </Avatar>
            </div>
          </header>
          {children}
          <Toaster />
        </div>
      </div>
    </SidebarProvider>

  );
}
